apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeshop

commonLabels:
  app: mongo

resources:
  - deployment.yaml
  - secret.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  # kubectl create configmap mongo-init-script --from-file=init-mongo.js -n kubeshop
