apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kubeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        command: ["redis-server"]
        args: ["--requirepass", "$(REDIS_PASSWORD)"]

      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - containerPort: 9121

      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
