apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeshop

commonLabels:
  app: redis

resources:
  - configmap.yaml
  - deployment.yaml
  - secret.yaml
  - service.yaml
  - pvc.yaml
