services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"  
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1.0"
        reservations:
          memory: "256M"
          cpus: "0.5"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    depends_on:
      - backend
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1.0"
        reservations:
          memory: "256M"
          cpus: "0.5"
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod","--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_APP_DB}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASS: ${MONGO_APP_PASS}
    volumes:
      -  mongo-ecommerce-data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          cpus: "2.0"  
          memory: "1G" 
        reservations:
          cpus: "1.0"  
          memory: "512M" 
  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    deploy:
      resources:
        limits:
          cpus: "1.0"  
          memory: "1G" 
        reservations:
          cpus: "0.5"  
          memory: "512M"
volumes:
   mongo-ecommerce-data:
   redis-data:

networks:
  ecommerce-network:
