services:
  backend:
    build:
      context: ./backend
    image: ${DOCKER_USERNAME}/kubeshop-backend:latest
    expose:
      - "3000"  # 👈 نستخدم expose بدل ports
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    networks:
      - kubeshop-network
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "1.0"
        reservations:
          memory: "512M"
          cpus: "0.5"

  frontend:
    image: ${DOCKER_USERNAME}/kubeshop-frontend:latest
    build:
      context: ./frontend
    expose:
      - "80"  
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=/api
    networks:
      - kubeshop-network
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1.0"
        reservations:
          memory: "256M"
          cpus: "0.5"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # 👈 البورت الوحيد المفتوح من خارج الشبكة
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # 👈 ملف إعدادات nginx
    depends_on:
      - frontend
      - backend
    networks:
      - kubeshop-network

networks:
  kubeshop-network:

volumes:
  mongo-kubeshop-data:
