# Global values
namespace: kubeshop

# Backend Configuration
backend:
  enabled: true
  image: adhamelganzoury/kubeshop-backend:latest
  replicaCount: 1
  servicePort: 3000
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
  secrets:
    # redisPassword: "adham2002"
    mongoUri: "mongodb://adham:adham2002@mongodb.kubeshop.svc.cluster.local:27017/ecommerce?authSource=ecommerce"
    jwtSecret: "adhamsomethingsecret"
    refreshTokenSecret: "adham2002"

# Frontend Configuration
frontend:
  image: adhamelganzoury/kubeshop-frontend:latest
  replicaCount: 1
  servicePort: 80
  containerPort: 5173
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
    requests:
      memory: "256Mi"
      cpu: "1"

# MongoDB Configuration
mongodb:
  image: adhamelganzoury/kubeshop-mongodb:latest
  replicaCount: 1
  mongoExpressImage: mongo-express:latest
  storageSize: 3Gi
  secrets:
    rootUser: root
    rootPassword: root2002
    database: ecommerce
    appUser: adham
    appPassword: adham2002

# Redis Configuration
# redis:
#   enabled: false
#   image: redis:latest
#   replicaCount: 1
#   storageSize: 1Gi
#   service:
#     name: redis
#     port: 6379
#   secrets:
#     password: "adham2002"  
ingress:
  enabled: true
  className: "nginx"
  host: kubeshop.local
#! helm upgrade ecommerce ./dist/ecommerce-platform-0.1.0.tgz --namespace kubeshop -f helm-chart/values.yaml
