apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: kubeshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
#! Note: Minikube automatically creates a PersistentVolume for us
