apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: kubeshop
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root2002
  MONGO_INITDB_DATABASE: ecommerce
  MONGO_APP_USER: adham
  MONGO_APP_PASS: adham2002
#! You can list all secrets: kubectl get secrets -n kubeshop
#! View all secret details: kubectl get secret mongo-secrets -n kubeshop -o yaml
