apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: {{ .Values.backend.env.redisHost | quote }}
  REDIS_PORT: {{ .Values.backend.env.redisPort | quote }}