apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.backend.secrets.redisPassword | quote }}
  MONGO_URI: {{ .Values.backend.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.backend.secrets.refreshTokenSecret | quote }}