# 1️⃣ Secret: Stores Redis password securely
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: kubeshop
type: Opaque
stringData:
  REDIS_PASSWORD: adham2002
---
# 2️⃣ PersistentVolumeClaim: Allocates storage for Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: kubeshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as needed
---
# 3️⃣ Deployment: Defines Redis and Redis Exporter containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kubeshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        command: ["redis-server"]
        args: ["--requirepass", "$(REDIS_PASSWORD)"]

      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - containerPort: 9121

      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
# 4️⃣ Service: Exposes Redis and Redis Exporter inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kubeshop
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: redis-exporter
    port: 9121
    targetPort: 9121
  type: ClusterIP  
