apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kubeshop
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: redis-exporter
    port: 9121
    targetPort: 9121
  type: ClusterIP
