apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kubeshop
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80  # Change from 5173 to 80 for ingress
    targetPort: 5173
  type: ClusterIP
