services:
  backend:
    # build:
    #   context: ../../src/backend
    image: adhamelganzoury/kubeshop-backend:latest
    expose:
      - "3000"
    environment:
      - MONGO_URI=mongodb+srv://adham54732:l3sfSf25TBFEGwmr@aaie.qzizwal.mongodb.net/Ecommerce?retryWrites=true&w=majority&appName=AAIE
      - JWT_SECRET=adhamsomethingsecret
      - REFRESH_TOKEN_SECRET=adham2002
    networks:
      - kubeshop-network
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "1.0"
        reservations:
          memory: "512M"
          cpus: "0.5"

  frontend:
    image: adhamelganzoury/kubeshop-frontend:latest
    # build:
    #   context: ../../src/frontend
    expose:
      - "80"
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL=/api
    networks:
      - kubeshop-network
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1.0"
        reservations:
          memory: "256M"
          cpus: "0.5"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf  # Correct path
    depends_on:
      - frontend
      - backend
    networks:
      - kubeshop-network

networks:
  kubeshop-network:
  
