apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.secrets.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.secrets.rootPassword | quote }}
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.secrets.database | quote }}
  MONGO_APP_USER: {{ .Values.mongodb.secrets.appUser | quote }}
  MONGO_APP_PASS: {{ .Values.mongodb.secrets.appPassword | quote }}