apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
    {{- if .Values.mongodb.mongoExpressImage }}
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
    {{- end }}
