name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  REPO_NAME: E-Commerce-Platform

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker compose build --no-cache
          docker compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_HOST: ${{ secrets.AWS_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible git

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 --decode > ~/.ssh/kubeshop-key.pem
          chmod 600 ~/.ssh/kubeshop-key.pem
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/deploy.yml \
            --extra-vars "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
            DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
            GITHUB_PAT=${{ secrets.GITHUB_PAT }} \
            ansible_user=${{ secrets.SSH_USERNAME }}"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"