name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  REPO_NAME: e-commerce-platform

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      instance_ips: ${{ steps.tf-output.outputs.ips }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infrastructure/terraform
        run: terraform init -input=false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Terraform Apply
        working-directory: ./infrastructure/terraform
        run: terraform apply -auto-approve -input=false

      - name: Extract Instance IPs
        id: tf-output
        working-directory: ./infrastructure/terraform
        run: |
          IPS=$(terraform output -raw instance_public_ips)
          echo "ips=$IPS" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images with Docker Compose
        working-directory: ./infrastructure/docker
        run: |
          docker buildx create --use
          docker-compose -f docker-compose.yaml build --build-arg BUILDKIT_INLINE_CACHE=1
          docker-compose -f docker-compose.yaml push

  deploy:
    needs: [terraform, build]
    runs-on: ubuntu-latest
    env:
      AWS_HOSTS: ${{ secrets.AWS_HOSTS }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible 

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 --decode > ~/.ssh/kubeshop-key.pem
          chmod 600 ~/.ssh/kubeshop-key.pem
          for ip in $(echo "${{ needs.terraform.outputs.instance_ips }}" | tr ',' ' '); do
              ssh-keyscan -H $ip >> ~/.ssh/known_hosts
          done

      - name: Generate dynamic inventory
        working-directory: ./infrastructure/ansible/inventory
        run: |
          echo "[production]" > hosts.ini
          for ip in $(echo "${{ needs.terraform.outputs.instance_ips }}" | tr ',' ' '); do
              echo "$ip ansible_user=ubuntu" >> hosts.ini
          done
          echo -e "\n[production:vars]" >> hosts.ini
          echo "ansible_ssh_private_key_file=~/.ssh/kubeshop-key.pem" >> hosts.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> hosts.ini

      - name: Run Ansible Playbook
        working-directory: ./infrastructure/ansible
        run: |
          ansible-playbook -i inventory/hosts.ini playbooks/deploy.yml \
            --extra-vars "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} \
            DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} \
            GITHUB_PAT=${{ secrets.GITHUB_PAT }}" -vvv
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
